# Generated by Django 2.1 on 2020-05-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200505_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.TextField(blank=True, choices=[('https://avataaars.io/?avatarStyle=Transparent&topType=LongHairBob&accessoriesType=Prescription02&hairColor=Platinum&facialHairType=Blank&clotheType=Hoodie&clotheColor=Gray01&eyeType=EyeRoll&eyebrowType=Default&mouthType=Default&skinColor=Light', 'Avatar 1'), ('https://avataaars.io/?avatarStyle=Transparent&topType=LongHairStraight&accessoriesType=Blank&hairColor=BrownDark&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light', 'Avatar 2'), ('https://avataaars.io/?avatarStyle=Transparent&topType=LongHairCurvy&accessoriesType=Prescription01&hairColor=Black&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Hearts&eyebrowType=RaisedExcitedNatural&mouthType=Smile&skinColor=Light', 'Avatar 3'), ('https://avataaars.io/?avatarStyle=Transparent&topType=Hat&accessoriesType=Round&facialHairType=Blank&clotheType=Hoodie&clotheColor=Black&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Tanned', 'Avatar 4'), ('https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShortFlat&accessoriesType=Prescription02&hairColor=Black&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Hearts&eyebrowType=RaisedExcitedNatural&mouthType=Smile&skinColor=Light', 'Avatar 5'), ('https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairDreads01&accessoriesType=Sunglasses&hairColor=Black&facialHairType=BeardMagestic&facialHairColor=Black&clotheType=CollarSweater&clotheColor=PastelBlue&eyeType=Hearts&eyebrowType=RaisedExcited&mouthType=Smile&skinColor=Light', 'Avatar 6')], verbose_name='Choose your Avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Write something about yourself'),
        ),
    ]
