# Generated by Django 2.1 on 2020-05-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200505_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('Science', (('bsc', 'BSc'), ('msc', 'MSc'))), ('Arts', (('ba', 'BA'), ('ma', 'MA'))), ('Commerce', (('bcom', 'BCom'), ('mcom', 'MCom'))), ('Engineering', (('btech', 'BTech'), ('mtech', 'MTech'))), ('Education', (('bed', 'BEd'), ('med', 'MEd'))), ('Research', (('phd', 'PhD'),))], max_length=250, verbose_name='Degree you are pursuing'),
        ),
    ]
