# Generated by Django 2.1 on 2020-05-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='university',
            field=models.CharField(blank=True, choices=[('cu', 'Calcutta University'), ('other', 'Other University')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('Science', (('bsc', 'BSc'), ('msc', 'MSc'))), ('Arts', (('ba', 'BA'), ('ma', 'MA'))), ('Commerce', (('bcom', 'BCom'), ('mcom', 'MCom'))), ('Engineering', (('btech', 'BTech'), ('mtech', 'MTech'))), ('Education', (('bed', 'BEd'), ('med', 'MEd'))), ('Research', (('phd', 'PhD'),))], max_length=250, verbose_name='If you are student, degree you are pursuing'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='honours',
            field=models.CharField(blank=True, max_length=50, verbose_name='Favourite subject'),
        ),
    ]
