# Generated by Django 2.1 on 2020-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200502_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
