# Generated by Django 2.1 on 2020-08-20 23:00

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200507_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_bleach.models.BleachField(),
        ),
    ]
