name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pipenv
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv shell
    - name: Install dependencies 
      shell: cmd
      run: |
        pipenv shell
        pipenv install --verbose --dev --skip-lock --python=${{ matrix.python }}
    - name: Run Tests
      shell: cmd
      run: |
        pipenv shell
        python manage.py test
